#weight_init: kaiming_normal
#score_init: None
dataset: electricity

weight_seed: 0
score_seed: 0
gpu: 2
batch_size: 128
model_type: 'Dense'
epochs: 50
weight_file: dense_ts_electricity

window_size: 200
dmodel: 512
forecast: True
save_scores: False
layer_norm: True
batch_norm: False
save_graphs: False

pos_enc: 'Standard'
lr: .001
scheduler: True
