#weight_init: kaiming_normal
#score_init: None
dataset: WTH

weight_seed: 0
score_seed: 0
gpu: 2
batch_size: 64

model_type: 'Sparse'
attention: 'Dense'

epochs: 50
weight_file: sparse_ts_wth

layer_norm_prune_rate: 0.5
lin_prune_rate: 0.5
attention_prune_rate: 0.5
has_src_mask: True

window_size: 200
dmodel: 512
forecast: True
save_scores: False
layer_norm: True
batch_norm: False
save_graphs: False

pos_enc: 'Standard'
lr: .001
#scheduler: True
#es_epochs: 5